### ISSUE TITLE
Use PGP key that corresponds to the email specified for registration

### ISSUE THREAD

**Issue by specious** [jcomeauictx/kybyz#6]
I've got multiple PGP keys on my keychain, one for `specious@gmail.com` and one for `isagdejev@protonmail.com`.

When I do:

`./kybyz.py register webninja isagdejev@protonmail.com`

GPG asks me for my passphrase for `specious@gmail.com`.

**Comment by specious** [comment]
Quite possibly because that key is listed before the other one when I run `gpg -K`.

**Comment by specious** [comment]
It think the solution is to use the `--default-key` option with `gpg`.

**Comment by jcomeauictx** [comment]
OK thanks I knew that code was sloppy and I had to improve it a few times already. I'll add `--default-key` and let you know.

**Comment by jcomeauictx** [comment]
Could you pull the latest and check?

**Comment by specious** [comment]
Just tested 26978375b3c6f42d0c7698c244ba83e5ece5196c and it uses the right key.

**Comment by jcomeauictx** [comment]
Thanks! Closing it for now, we'll likely have to reopen it somewhere down the line.
