### ISSUE TITLE
Doesn't pass validation when using development build of GnuPG

### ISSUE THREAD

**Issue by specious** [jcomeauictx/kybyz#7]
I'm currently using the development build of GnuPG, which insists on printing warnings about it:

```
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
gpg: Signature made Fri 24 Dec 2021 10:11:42 AM EST
gpg:                using EDDSA key 43C0A03BCA679F3F85FD52538ED65C1EAB79A2D8
gpg:                issuer "isagdejev@protonmail.com"
gpg: Good signature from "Ildar Sagdejev (Software manufacturing in progress) <isagdejev@protonmail.com>" [ultimate]
```

So the verification throws on this line, because the first line of the output is not what it expects:

https://github.com/jcomeauictx/kybyz/blob/26978375b3c6f42d0c7698c244ba83e5ece5196c/kbutils.py#L125

**Comment by specious** [comment]
Changing `output[0]` to `"\n".join(output)` didn't work either because it still doesn't find what it expects.

**Comment by specious** [comment]
Also, this only works if GPG is in English:

https://github.com/jcomeauictx/kybyz/blob/26978375b3c6f42d0c7698c244ba83e5ece5196c/kbutils.py#L124

If I run:

```
LANGUAGE="es" ./kybyz.py register webninja isagdejev@protonmail.com
```

GnuPG outputs:

```
gpg: NOTE: THIS IS A DEVELOPMENT VERSION!
gpg: It is only intended for test purposes and should NOT be
gpg: used in a production environment or with production keys!
gpg: Firmado el Fri 24 Dec 2021 10:22:03 AM EST
gpg:                usando EDDSA clave 43C0A03BCA679F3F85FD52538ED65C1EAB79A2D8
gpg:                emisor "isagdejev@protonmail.com"
gpg: Firma correcta de "Ildar Sagdejev (Software manufacturing in progress) <isagdejev@protonmail.com>" [absoluta]
```

**Comment by specious** [comment]
I just tried the [python-gnupg](https://github.com/vsajip/python-gnupg) module and it seems to work:

```
$ ipython
Python 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from gnupg import GPG

In [2]: gpg = GPG()

In [3]: sig = gpg.sign("", keyid="isagdejev@protonmail.com")

In [4]: sig.returncode
Out[4]: 0

In [5]: sig.fingerprint
Out[5]: '43C0A03BCA679F3F85FD52538ED65C1EAB79A2D8'

In [6]: verification = gpg.verify(sig.data)

In [7]: verification.returncode
Out[7]: 0
```

**Comment by specious** [comment]
It works with my development gpg version, and it works with different languages.

```
$ gpg --version | head -5
gpg (GnuPG) 2.3.2-beta105
libgcrypt 1.9.4-unknown
NOTE: THIS IS A DEVELOPMENT VERSION!
It is only intended for test purposes and should NOT be
used in a production environment or with production keys!
```

**Comment by specious** [comment]
That library seems to be well maintained and up-to-date. I'm not sure where the latest docs are published but I just [found](https://github.com/vsajip/python-gnupg/blob/1ec9ca28946460dfe5c5987d9ebeca62e956f894/docs/index.rst#signing) what's included in the `docs/` directory.

I hope this helps make it work for everybody.

**Comment by specious** [comment]
Oh... of course:

```
$ pip show python-gnupg          
Name: python-gnupg
Version: 0.4.8
Summary: A wrapper for the Gnu Privacy Guard (GPG or GnuPG)
Home-page: https://docs.red-dove.com/python-gnupg/
...
```

Docs: https://docs.red-dove.com/python-gnupg/

**Comment by jcomeauictx** [comment]
I was having multiple problems with python-gnupg, which is why I "rolled my own" replacement. Unfortunately the size of commit messages in git didn't permit me to explain well, and I tend to forget things quickly, so I can't say exactly what was failing. What I *can* do is to import gnupg, which if successful will take over, and reserve my fallback code for those whose systems cannot access a compatible python-gnupg module. Will that work?

**Comment by specious** [comment]
Probably. I had to `pip install python-gnupg` so it's probably going to be an explicit dependency for most people (e.g. something listed in `requirements.txt`).

**Comment by jcomeauictx** [comment]
If you have a system on which it *will* install and run, please focus on that for now. My focus is on depth, trying to get a basic code functionality, before I deal with breadth, expanding the range of systems on which it runs.

**Comment by specious** [comment]
It looks like without modifying the code, I would need a compatible version of GnuPG and I would also need an RSA key, instead of my main key which is EDDSA.

Because here it checks for `using RSA key`:

https://github.com/jcomeauictx/kybyz/blob/26978375b3c6f42d0c7698c244ba83e5ece5196c/kbutils.py#L128

I can set all that up, but maybe I can just patch the code to let me through for now.

**Comment by specious** [comment]
I see what you're saying about maybe making python-gnupg an optional dependency.

**Comment by jcomeauictx** [comment]
I can't get python-gnupg to work at all on either Debian Buster or Bullseye, and the documentation isn't detailed enough for me to know what it returns for various calls. Nevertheless, the latest update might work with it, but I don't yet have the code in place for `--default-key`.

**Comment by specious** [comment]
Just tried 2ca59915af141bc425b2c6f9445cbaf6fa74a310, and `./kybyz.py register <name> <email>` isn't choosing the key associated with `<email>` for verification.

It looks like here it would need to pass `email` to `gpg.sign()` as `gpg.sign('', keyid=email)`:

https://github.com/jcomeauictx/kybyz/blob/2ca59915af141bc425b2c6f9445cbaf6fa74a310/kbutils.py#L177-L190

**Comment by jcomeauictx** [comment]
Did you test it? I suspect python-gnupg only accepts a hexadecimal string for keyid. I can't test because gnupg doesn't work with my version of gpg.

**Comment by specious** [comment]
Yeah, with this change it picks the right key:

```diff
diff --git a/kbutils.py b/kbutils.py
index 04cb40c..1a60d0f 100755
--- a/kbutils.py
+++ b/kbutils.py
@@ -181,7 +181,7 @@ def verify_key(email):
     gpgkey = None
     gpg = GPG()
     # pylint: disable=no-member
-    verified = gpg.verify(gpg.sign('').data)
+    verified = gpg.verify(gpg.sign('', keyid=email).data)
     logging.debug('verified: %s', verified)
     if not verified.username.endswith('<' + email + '>'):
         raise ValueError('%s no match for GPG certificate %s' %
```

And after the verification it goes all the way:

```
...
DEBUG:root:verified: <gnupg.Verify object at 0x7f5ad467c100>
INFO:root:Now registered as webninja isagdejev@protonmail.com
None
```

**Comment by specious** [comment]
As far as I can tell, python-gnupg is just a wrapper for calling gpg, and just passes the key id value directly to it:

https://github.com/vsajip/python-gnupg/blob/1a6acab/gnupg.py#L1146-L1147

**Comment by specious** [comment]
How exactly is it failing on the debian system you're using?

**Comment by jcomeauictx** [comment]
It doesn't even recognize my keys. It's looking for them in files that don't exist on recent versions of gpg.

**Comment by specious** [comment]
Hm, that's interesting. It seems like it should just be executing whichever gpg binary you've got installed and letting it handle its business however it does:

https://github.com/vsajip/python-gnupg/blob/1a6acab/gnupg.py#L870

**Comment by jcomeauictx** [comment]
I'm using the pip-installed version. It's out of date. And it gives this error with keyid:

TypeError: _sign_file() got an unexpected keyword argument 'keyid'

**Comment by jcomeauictx** [comment]
Nevertheless I've pushed the commit.

**Comment by specious** [comment]
Looking at what's [available](https://pypi.org/search/?q=gnupg) from pypi, I bet it's possible I'm using `python-gnupg` 0.4.8 and you've got `gnupg` 2.3.1, both installed with pip.

The second package is indeed an out-of-date [forked](https://github.com/isislovecruft/python-gnupg) version of the first.

**Comment by jcomeauictx** [comment]
That's it! That's what I was doing wrong. Thank you.

**Comment by specious** [comment]
I bet so many people are confusing the two packages.

It looks like [isislovecruft/python-gnupg](https://github.com/isislovecruft/python-gnupg) has been a good project in its own right, just hasn't been actively maintained as of late. The code was forked from a much earlier version of what is now [vsajip/python-gnupg](https://github.com/vsajip/python-gnupg) back in 2013.
