### ISSUE TITLE
Getting it to work on a non-debian system

### ISSUE THREAD

**Issue by specious** [jcomeauictx/kybyz#8]
I just thought I'd share exactly what I did to get it to run:

```
pip install --user python-gnupg pylint uwsgi
```

There doesn't appear to be anything distro-specific required, it's just an option to use distro packages vs pip.

**Comment by specious** [comment]
Although, I also didn't have `pylint3` by that name, which is expected by:

https://github.com/jcomeauictx/kybyz/blob/3d4e13a052a2a210a02c1838293495679551da1c/Makefile#L5

So, I fixed it by making a symlink:

```
ln -s `which pylint` ~/.local/bin/pylint3
```

**Comment by jcomeauictx** [comment]
The makefile should have created the symlink.

**Comment by jcomeauictx** [comment]
I figure if I give, in the README, a working method of getting it running on a particular system, that's good enough documentation for anyone to figure it out for their own system. At least for now, we're still pre-alpha.

**Comment by specious** [comment]
When I ran `make`, it got to:

```
which pylint3 || sudo apt-get install pylint3
[sudo] password for me: 
```

**Comment by jcomeauictx** [comment]
and fails after you type the password?

**Comment by specious** [comment]
> I figure if I give, in the README, a working method of getting it running on a particular system, that's good enough documentation for anyone to figure it out for their own system. At least for now, we're still pre-alpha.

Yeah, I just figured I'd share the non-distro-specific solution.

**Comment by specious** [comment]
> and fails after you type the password?

Of course:

```
sudo: apt-get: command not found
```

**Comment by jcomeauictx** [comment]
Oh OK, I forgot you're not using Debian.

**Comment by specious** [comment]
I don't think there's anything too distro-specific in the requirements. It's just a matter of how you get the dependencies.

**Comment by jcomeauictx** [comment]
Of course, but all these are distractions to me. I want to work on the functionality of the software.

**Comment by specious** [comment]
No problem. I just wanted to share the solution.

**Comment by jcomeauictx** [comment]
Once I work out the basics of posting, commenting, and reactions, I'll be willing to work on expanding it to other systems.

**Comment by specious** [comment]
I got to the prompt, and it opens in the browser.

![kybyz-screenshot-2021-12-29-19:27:57](https://user-images.githubusercontent.com/451178/147714204-74f230b6-ee27-45d4-8508-eb0bb65d0557.png)

**Comment by jcomeauictx** [comment]
Cool!

**Comment by jcomeauictx** [comment]
But I see my css doesn't work on your system...

**Comment by specious** [comment]
It opens the browser page and after several seconds I get the prompt:

```
INFO:root:Ready to accept commands; `quit` to terminate input loop
INFO:root:no command received to process
None
kbz> 
```

But then if I just wait about half a minute, it starts printing:

```
...
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
INFO:root:received: '', length: 0
```

Ad infinitum.

**Comment by specious** [comment]
I've imported and signed your PGP key. When I run:

```
send jcomeauictx jc@unternet.net it works
```

It again chooses the wrong PGP key (not the one I ran `register` with).

**Comment by jcomeauictx** [comment]
I've gotten that `INFO:root:received: '', length: 0` problem once before. It's an intermittent issue, I'll need to track it down someday.

And I need to add the `keyid` or `--default-key` code to every gpg call that requires it.

**Comment by jcomeauictx** [comment]
But it's not going to happen tonight.

**Comment by specious** [comment]
> I've gotten that `INFO:root:received: '', length: 0` problem once before. It's an intermittent issue, I'll need to track it down someday.

I can easily reproduce this issue.

**Comment by specious** [comment]
> But I see my css doesn't work on your system...

How off is the styling?

**Comment by specious** [comment]
The output is clearly coming from `ircbot.py`. It just floods my terminal.

**Comment by specious** [comment]
For what it's worth, before I get the `kbz>` prompt, I get:

```
INFO:root:received: ':irc.smutfairy.com NOTICE * :*** Looking up your hostname', length: 57
INFO:root:received: ':irc.smutfairy.com NOTICE * :*** Found your hostname', length: 52
INFO:root:received: ':irc.smutfairy.com 461 * USER :Not enough parameters', length: 52
INFO:root:received: ':irc.smutfairy.com 451 webninja :You have not registered', length: 56
```

**Comment by jcomeauictx** [comment]
"How off is the styling?"

The text should have fit the square div.

**Comment by specious** [comment]
Oh, it does that if I fullscreen the window.

**Comment by specious** [comment]
I just experimented with the style code in the browser. The font scales with the image when I try something like this:

```css
.netmeme p {
  font-size: calc((44vw - 1rem) / 10);
}
```

To prevent overflows when it doesn't work:

```css
.netmeme {
  overflow: hidden;
}
```

**Comment by jcomeauictx** [comment]
Closing this after Makefile and README updated for CentOs, which should be sufficient to extrapolate to other distributions. I split off the empty string problem to another issue.
